<?php

namespace App\Platform\Core\PageBuilder;

class SchemaFirstWidgetSchemas
{
    /**
     * @return array<string, array<string, mixed>>
     */
    public function definitions(): array
    {
        return [
            'container' => [
                'type' => 'container',
                'label' => 'Container',
                'icon' => 'square',
                'category' => 'Schema First',
                'default_props' => [
                    'semantic_tag' => 'section',
                    'direction' => 'column',
                    'wrap' => 'nowrap',
                    'justify' => 'flex-start',
                    'align' => 'stretch',
                    'gap' => '24px',
                    'content_width' => 'boxed',
                    'min_height' => '120px',
                    'background' => '',
                    'border_width' => '0px',
                    'border_style' => 'solid',
                    'border_color' => '',
                    'radius' => '',
                    'shadow' => 'none',
                    'overflow' => 'visible',
                    'responsive_visibility' => 'all',
                ],
                'general_schema' => [
                    $this->control('semantic_tag', 'Semantic tag', 'general', 'Structure', 'select', 'section', null, 'wrapper', 'html_tag'),
                    $this->control('direction', 'Direction', 'general', 'Layout', 'select', 'column', 'flex-direction', 'wrapper', 'flex_direction'),
                    $this->control('wrap', 'Wrap', 'general', 'Layout', 'select', 'nowrap', 'flex-wrap', 'wrapper', 'flex_wrap'),
                    $this->control('justify', 'Justify', 'general', 'Layout', 'select', 'flex-start', 'justify-content', 'wrapper', 'justify_content'),
                    $this->control('align', 'Align', 'general', 'Layout', 'select', 'stretch', 'align-items', 'wrapper', 'align_items'),
                    $this->control('gap', 'Gap', 'general', 'Layout', 'text', '24px', 'gap', 'wrapper', 'css_size'),
                    $this->control('content_width', 'Content width', 'general', 'Layout', 'select', 'boxed', null, 'wrapper', 'content_width'),
                    $this->control('min_height', 'Min height', 'general', 'Layout', 'text', '120px', 'min-height', 'wrapper', 'css_size'),
                    $this->control('display', 'Display', 'general', 'Layout', 'hidden', 'flex', 'display', 'wrapper', 'display'),
                ],
                'style_schema' => [
                    $this->control('background', 'Background', 'style', 'Background', 'color', '', 'background-color', 'wrapper', 'color'),
                    $this->control('border_width', 'Border width', 'style', 'Border', 'text', '0px', 'border-width', 'wrapper', 'css_size'),
                    $this->control('border_style', 'Border style', 'style', 'Border', 'select', 'solid', 'border-style', 'wrapper', 'border_style'),
                    $this->control('border_color', 'Border color', 'style', 'Border', 'color', '', 'border-color', 'wrapper', 'color'),
                    $this->control('radius', 'Radius', 'style', 'Border', 'text', '', 'border-radius', 'wrapper', 'css_size'),
                    $this->control('shadow', 'Shadow', 'style', 'Effects', 'select', 'none', 'box-shadow', 'wrapper', 'box_shadow'),
                    $this->control('overflow', 'Overflow', 'style', 'Effects', 'select', 'visible', 'overflow', 'wrapper', 'overflow'),
                ],
                'advanced_schema' => $this->advanced(),
                'supports' => ['children' => true, 'responsive' => true, 'style_engine' => true],
                'editor_preview_renderer' => 'schema-first.editor.container',
                'frontend_renderer_reference' => SchemaFirstLaravelRenderer::class.'@container',
            ],
            'heading' => [
                'type' => 'heading',
                'label' => 'Heading',
                'icon' => 'type',
                'category' => 'Schema First',
                'default_props' => [
                    'text' => 'Heading text',
                    'html_tag' => 'h2',
                    'font_family' => 'inherit',
                    'font_size' => '',
                    'font_weight' => '700',
                    'line_height' => '',
                    'letter_spacing' => '',
                    'alignment' => 'left',
                    'responsive_visibility' => 'all',
                ],
                'general_schema' => [
                    $this->control('text', 'Text', 'general', 'Content', 'text', 'Heading text', null, 'content', 'plain_text'),
                    $this->control('html_tag', 'HTML tag', 'general', 'Structure', 'select', 'h2', null, 'content', 'heading_tag'),
                    $this->control('link', 'Link', 'general', 'Link', 'text', '', null, 'content', 'url'),
                ],
                'style_schema' => [
                    $this->control('font_family', 'Font family', 'style', 'Typography', 'select', 'inherit', 'font-family', 'content', 'font_family'),
                    $this->control('font_size', 'Font size', 'style', 'Typography', 'text', '', 'font-size', 'content', 'css_size'),
                    $this->control('font_weight', 'Font weight', 'style', 'Typography', 'select', '700', 'font-weight', 'content', 'font_weight'),
                    $this->control('line_height', 'Line height', 'style', 'Typography', 'text', '', 'line-height', 'content', 'css_size'),
                    $this->control('letter_spacing', 'Letter spacing', 'style', 'Typography', 'text', '', 'letter-spacing', 'content', 'css_size'),
                    $this->control('color', 'Color', 'style', 'Typography', 'color', '', 'color', 'content', 'color'),
                    $this->control('alignment', 'Alignment', 'style', 'Typography', 'select', 'left', 'text-align', 'content', 'text_align'),
                    $this->control('text_transform', 'Text transform', 'style', 'Typography', 'select', 'none', 'text-transform', 'content', 'text_transform'),
                    $this->control('text_decoration', 'Text decoration', 'style', 'Typography', 'select', 'none', 'text-decoration', 'content', 'text_decoration'),
                ],
                'advanced_schema' => $this->advanced(),
                'supports' => ['children' => false, 'responsive' => true, 'style_engine' => true],
                'editor_preview_renderer' => 'schema-first.editor.heading',
                'frontend_renderer_reference' => SchemaFirstLaravelRenderer::class.'@heading',
            ],
            'image' => [
                'type' => 'image',
                'label' => 'Image',
                'icon' => 'image',
                'category' => 'Schema First',
                'default_props' => [
                    'media_id' => '',
                    'media_url' => '',
                    'image_url' => '',
                    'thumbnail_url' => '',
                    'media_width' => '',
                    'media_height' => '',
                    'mime_type' => '',
                    'alt' => '',
                    'caption_mode' => 'none',
                    'caption' => '',
                    'link_type' => 'none',
                    'link_url' => '',
                    'link_target' => '_self',
                    'link_nofollow' => 'false',
                    'loading' => 'lazy',
                    'decoding' => 'async',
                    'width' => '',
                    'max_width' => '100%',
                    'height' => '',
                    'object_fit' => 'cover',
                    'object_position' => 'center',
                    'border_width' => '0px',
                    'border_style' => 'solid',
                    'border_color' => '',
                    'border_radius' => '',
                    'shadow' => 'none',
                    'opacity' => '1',
                    'alignment' => 'center',
                    'caption_color' => '',
                    'caption_font_size' => '',
                    'caption_alignment' => 'center',
                    'caption_spacing' => '8px',
                    'responsive_visibility' => 'all',
                ],
                'general_schema' => [
                    $this->control('media_url', 'Image source', 'general', 'Image Source', 'media', '', null, 'image', 'media_url'),
                    $this->control('media_id', 'Media ID', 'general', 'Image Source', 'hidden', '', null, 'wrapper', 'string'),
                    $this->control('image_url', 'Image URL', 'general', 'Image Source', 'hidden', '', null, 'wrapper', 'media_url'),
                    $this->control('thumbnail_url', 'Thumbnail URL', 'general', 'Image Source', 'hidden', '', null, 'wrapper', 'media_url'),
                    $this->control('media_width', 'Media width', 'general', 'Image Source', 'hidden', '', null, 'wrapper', 'number'),
                    $this->control('media_height', 'Media height', 'general', 'Image Source', 'hidden', '', null, 'wrapper', 'number'),
                    $this->control('mime_type', 'Mime type', 'general', 'Image Source', 'hidden', '', null, 'wrapper', 'string'),
                    $this->control('alt', 'Alt text', 'general', 'Image Source', 'text', '', null, 'image', 'plain_text'),
                    $this->control('caption_mode', 'Caption', 'general', 'Caption', 'select', 'none', null, 'wrapper', 'string'),
                    $this->control('caption', 'Custom caption', 'general', 'Caption', 'text', '', null, 'content', 'plain_text'),
                    $this->control('link_type', 'Link type', 'general', 'Link', 'select', 'none', null, 'wrapper', 'string'),
                    $this->control('link_url', 'Custom URL', 'general', 'Link', 'text', '', null, 'wrapper', 'url'),
                    $this->control('link_target', 'Open link', 'general', 'Link', 'select', '_self', null, 'wrapper', 'string'),
                    $this->control('link_nofollow', 'Rel nofollow', 'general', 'Link', 'switch', 'false', null, 'wrapper', 'boolean'),
                    $this->control('loading', 'Loading', 'general', 'Image Loading', 'select', 'lazy', null, 'image', 'string'),
                    $this->control('decoding', 'Decoding', 'general', 'Image Loading', 'select', 'async', null, 'image', 'string'),
                ],
                'style_schema' => [
                    $this->control('width', 'Width', 'style', 'Size', 'text', '', 'width', 'image', 'css_size'),
                    $this->control('max_width', 'Max width', 'style', 'Size', 'text', '100%', 'max-width', 'image', 'css_size'),
                    $this->control('height', 'Height', 'style', 'Size', 'text', '', 'height', 'image', 'css_size'),
                    $this->control('object_fit', 'Object fit', 'style', 'Size', 'select', 'cover', 'object-fit', 'image', 'object_fit'),
                    $this->control('object_position', 'Object position', 'style', 'Size', 'select', 'center', 'object-position', 'image', 'object_position'),
                    $this->control('alignment', 'Alignment', 'style', 'Alignment', 'select', 'center', 'text-align', 'wrapper', 'text_align'),
                    $this->control('border_width', 'Border width', 'style', 'Border', 'text', '0px', 'border-width', 'image', 'css_size'),
                    $this->control('border_style', 'Border style', 'style', 'Border', 'select', 'solid', 'border-style', 'image', 'border_style'),
                    $this->control('border_color', 'Border color', 'style', 'Border', 'color', '', 'border-color', 'image', 'color'),
                    $this->control('border_radius', 'Border radius', 'style', 'Border', 'text', '', 'border-radius', 'image', 'css_size_group'),
                    $this->control('opacity', 'Opacity', 'style', 'Effects', 'select', '1', 'opacity', 'image', 'number'),
                    $this->control('shadow', 'Shadow', 'style', 'Effects', 'select', 'none', 'box-shadow', 'image', 'box_shadow'),
                    $this->control('caption_color', 'Caption color', 'style', 'Caption', 'color', '', 'color', 'caption', 'color'),
                    $this->control('caption_font_size', 'Caption font size', 'style', 'Caption', 'text', '', 'font-size', 'caption', 'css_size'),
                    $this->control('caption_alignment', 'Caption alignment', 'style', 'Caption', 'select', 'center', 'text-align', 'caption', 'text_align'),
                    $this->control('caption_spacing', 'Caption spacing', 'style', 'Caption', 'text', '8px', 'margin-top', 'caption', 'css_size'),
                ],
                'advanced_schema' => $this->advanced(),
                'supports' => ['children' => false, 'responsive' => true, 'style_engine' => true],
                'editor_preview_renderer' => 'schema-first.editor.image',
                'frontend_renderer_reference' => SchemaFirstLaravelRenderer::class.'@image',
            ],
            'text' => [
                'type' => 'text',
                'component_type' => 'pb_text',
                'label' => 'Text',
                'icon' => 'align-left',
                'category' => 'Basic',
                'default_props' => [
                    'text' => 'Text content',
                    'html_tag' => 'p',
                    'link' => '',
                    'font_family' => 'inherit',
                    'font_size' => '',
                    'font_weight' => '400',
                    'line_height' => '',
                    'letter_spacing' => '',
                    'color' => '',
                    'alignment' => 'left',
                    'text_transform' => 'none',
                    'text_decoration' => 'none',
                    'responsive_visibility' => 'all',
                ],
                'general_schema' => [
                    $this->control('text', 'Text', 'general', 'Content', 'textarea', 'Text content', null, 'content', 'plain_text'),
                    $this->control('html_tag', 'HTML tag', 'general', 'Structure', 'select', 'p', null, 'content', 'text_tag'),
                    $this->control('link', 'Link', 'general', 'Link', 'text', '', null, 'content', 'url'),
                ],
                'style_schema' => [
                    $this->control('font_family', 'Font family', 'style', 'Typography', 'select', 'inherit', 'font-family', 'content', 'font_family'),
                    $this->control('font_size', 'Font size', 'style', 'Typography', 'text', '', 'font-size', 'content', 'css_size'),
                    $this->control('font_weight', 'Font weight', 'style', 'Typography', 'select', '400', 'font-weight', 'content', 'font_weight'),
                    $this->control('line_height', 'Line height', 'style', 'Typography', 'text', '', 'line-height', 'content', 'css_size'),
                    $this->control('letter_spacing', 'Letter spacing', 'style', 'Typography', 'text', '', 'letter-spacing', 'content', 'css_size'),
                    $this->control('color', 'Color', 'style', 'Typography', 'color', '', 'color', 'content', 'color'),
                    $this->control('alignment', 'Alignment', 'style', 'Typography', 'select', 'left', 'text-align', 'content', 'text_align'),
                    $this->control('text_transform', 'Text transform', 'style', 'Typography', 'select', 'none', 'text-transform', 'content', 'text_transform'),
                    $this->control('text_decoration', 'Text decoration', 'style', 'Typography', 'select', 'none', 'text-decoration', 'content', 'text_decoration'),
                ],
                'advanced_schema' => $this->advanced(),
                'supports' => ['children' => false, 'responsive' => true, 'style_engine' => true],
                'editor_preview_renderer' => 'schema-first.editor.text',
                'frontend_renderer_reference' => SchemaFirstLaravelRenderer::class.'@text',
            ],
            'button' => [
                'type' => 'button',
                'component_type' => 'pb_button',
                'label' => 'Button',
                'icon' => 'mouse-pointer-click',
                'category' => 'Basic',
                'default_props' => [
                    'text' => 'Button',
                    'link_url' => '#',
                    'link_target' => '_self',
                    'font_family' => 'inherit',
                    'font_size' => '',
                    'font_weight' => '600',
                    'text_color' => '#ffffff',
                    'background_color' => '#111827',
                    'hover_text_color' => '#ffffff',
                    'hover_background_color' => '#374151',
                    'alignment' => 'left',
                    'width_mode' => 'auto',
                    'width' => '',
                    'padding' => '12px 18px 12px 18px',
                    'border_width' => '0px',
                    'border_style' => 'solid',
                    'border_color' => '',
                    'border_radius' => '6px 6px 6px 6px',
                    'shadow' => 'none',
                    'responsive_visibility' => 'all',
                ],
                'general_schema' => [
                    $this->control('text', 'Text', 'general', 'Content', 'text', 'Button', null, 'button', 'plain_text'),
                    $this->control('link_url', 'Link URL', 'general', 'Link', 'text', '#', null, 'button', 'url'),
                    $this->control('link_target', 'Target', 'general', 'Link', 'select', '_self', null, 'button', 'string'),
                ],
                'style_schema' => [
                    $this->control('font_family', 'Font family', 'style', 'Typography', 'select', 'inherit', 'font-family', 'button', 'font_family'),
                    $this->control('font_size', 'Font size', 'style', 'Typography', 'text', '', 'font-size', 'button', 'css_size'),
                    $this->control('font_weight', 'Font weight', 'style', 'Typography', 'select', '600', 'font-weight', 'button', 'font_weight'),
                    $this->control('text_color', 'Text color', 'style', 'Colors', 'color', '#ffffff', 'color', 'button', 'color'),
                    $this->control('background_color', 'Background color', 'style', 'Colors', 'color', '#111827', 'background-color', 'button', 'color'),
                    $this->control('hover_text_color', 'Hover text color', 'style', 'Hover', 'color', '#ffffff', null, 'button', 'color'),
                    $this->control('hover_background_color', 'Hover background color', 'style', 'Hover', 'color', '#374151', null, 'button', 'color'),
                    $this->control('alignment', 'Alignment', 'style', 'Layout', 'select', 'left', 'text-align', 'wrapper', 'text_align'),
                    $this->control('width_mode', 'Width', 'style', 'Layout', 'select', 'auto', null, 'button', 'button_width_mode'),
                    $this->control('width', 'Custom width', 'style', 'Layout', 'text', '', 'width', 'button', 'css_size'),
                    $this->control('padding', 'Padding', 'style', 'Spacing', 'text', '12px 18px 12px 18px', 'padding', 'button', 'css_size_group'),
                    $this->control('border_width', 'Border width', 'style', 'Border', 'text', '0px', 'border-width', 'button', 'css_size'),
                    $this->control('border_style', 'Border style', 'style', 'Border', 'select', 'solid', 'border-style', 'button', 'border_style'),
                    $this->control('border_color', 'Border color', 'style', 'Border', 'color', '', 'border-color', 'button', 'color'),
                    $this->control('border_radius', 'Border radius', 'style', 'Border', 'text', '6px 6px 6px 6px', 'border-radius', 'button', 'css_size_group'),
                    $this->control('shadow', 'Shadow', 'style', 'Effects', 'select', 'none', 'box-shadow', 'button', 'box_shadow'),
                ],
                'advanced_schema' => $this->advanced(false),
                'supports' => ['children' => false, 'responsive' => true, 'style_engine' => true],
                'editor_preview_renderer' => 'schema-first.editor.button',
                'frontend_renderer_reference' => SchemaFirstLaravelRenderer::class.'@button',
            ],
            'divider' => [
                'type' => 'divider',
                'component_type' => 'pb_divider',
                'label' => 'Divider',
                'icon' => 'minus',
                'category' => 'Basic',
                'default_props' => [
                    'width' => '100%',
                    'alignment' => 'center',
                    'line_style' => 'solid',
                    'line_color' => '#d1d5db',
                    'thickness' => '1px',
                    'spacing_top' => '12px',
                    'spacing_bottom' => '12px',
                    'responsive_visibility' => 'all',
                ],
                'general_schema' => [
                    $this->control('width', 'Width', 'general', 'Layout', 'text', '100%', 'width', 'line', 'css_size'),
                    $this->control('alignment', 'Alignment', 'general', 'Layout', 'select', 'center', 'justify-content', 'wrapper', 'justify_content'),
                ],
                'style_schema' => [
                    $this->control('line_style', 'Line style', 'style', 'Line', 'select', 'solid', 'border-top-style', 'line', 'border_style'),
                    $this->control('line_color', 'Line color', 'style', 'Line', 'color', '#d1d5db', 'border-top-color', 'line', 'color'),
                    $this->control('thickness', 'Thickness', 'style', 'Line', 'text', '1px', 'border-top-width', 'line', 'css_size'),
                    $this->control('spacing_top', 'Spacing top', 'style', 'Spacing', 'text', '12px', 'padding-top', 'wrapper', 'css_size'),
                    $this->control('spacing_bottom', 'Spacing bottom', 'style', 'Spacing', 'text', '12px', 'padding-bottom', 'wrapper', 'css_size'),
                ],
                'advanced_schema' => $this->advanced(false),
                'supports' => ['children' => false, 'responsive' => true, 'style_engine' => true],
                'editor_preview_renderer' => 'schema-first.editor.divider',
                'frontend_renderer_reference' => SchemaFirstLaravelRenderer::class.'@divider',
            ],
        ];
    }

    /**
     * @return array<string, mixed>
     */
    private function control(
        string $key,
        string $label,
        string $tab,
        string $group,
        string $type,
        mixed $default = '',
        ?string $cssProperty = null,
        string $target = 'wrapper',
        string $sanitize = 'string'
    ): array {
        return [
            'key' => $key,
            'label' => $label,
            'tab' => $tab,
            'group' => $group,
            'type' => $type,
            'default' => $default,
            'cssProperty' => $cssProperty,
            'target' => $target,
            'sanitize' => $sanitize,
            'schema_first' => true,
        ];
    }

    /**
     * @return array<int, array<string, mixed>>
     */
    private function advanced(bool $includePadding = true): array
    {
        $controls = [
            $this->control('margin', 'Margin', 'advanced', 'Spacing', 'text', '', 'margin', 'wrapper', 'css_size_group'),
        ];

        if ($includePadding) {
            $controls[] = $this->control('padding', 'Padding', 'advanced', 'Spacing', 'text', '', 'padding', 'wrapper', 'css_size_group');
        }

        $controls[] = $this->control('css_id', 'CSS ID', 'advanced', 'Identity', 'text', '', null, 'wrapper', 'html_id');
        $controls[] = $this->control('css_class', 'CSS class', 'advanced', 'Identity', 'text', '', null, 'wrapper', 'class_list');
        $controls[] = $this->control('responsive_visibility', 'Responsive visibility', 'advanced', 'Responsive', 'select', 'all', null, 'wrapper', 'visibility');

        return $controls;
    }
}
